import { NextResponse } from 'next/server';

export async function POST(req: Request) {
    try {
        const { topic, difficulty, length, tone } = await req.json();

        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost:3000",
                "X-Title": "SwiftRead AI"
            },
            body: JSON.stringify({
                "model": "openrouter/free",
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a reading practice text generator. Output ONLY raw text. No chat, no markdown headers, no conversational filler."
                    },
                    {
                        "role": "user",
                        "content": `Generate a reading passage about "${topic}". Level: ${difficulty}. Length: ${length}. Tone: ${tone}.`
                    }
                ]
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error("OpenRouter Response Error:", errorText);
            throw new Error(`OpenRouter API error: ${response.status} ${response.statusText}`);
        }

        const data = await response.json();
        if (!data.choices || data.choices.length === 0) {
            throw new Error("No text generated by AI.");
        }

        return NextResponse.json({ text: data.choices[0].message.content });
    } catch (error: any) {
        console.error("Route Error Details:", error.message);
        return NextResponse.json({ error: error.message || "Failed to generate text" }, { status: 500 });
    }
}
